name: PickupSpawners
version: ${project.version}
main: me.poma123.spawners.PickupSpawners
api-version: 1.13
softdepend: [Vault]
permissions:
  spawnerlimit.bypass:
    default: op
  pickupspawners.give:
    default: op
  pickupspawners.additem:
    default: op
  pickupspawners.removeitem:
    default: op
  pickupspawners.itemlist:
    default: op
  pickupspawners.signshop.use:
    default: true
  pickupspawners.signshop.create:
    default: op
  pickupspawners.gui:
    default: op
  pickupspawners.change:
    default: op
  pickupspawners.updateitem:
    default: op
  pickupspawners.setitempermission:
    default: op
  pickupspawners.removeitempermission:
    default: op
  pickupspawners.bypasspickupblock:
    default: op
  pickupspawners.breaklimit.default:
    default: true
  pickupspawners.place:
    default: true
commands:
  pickupspawners:
    usage: /<command>
    description: PickupSpawners main command
    aliases: [spawners, pspawners, pickups]